In [8]:
import numpy as np

from bandit import Bandit

In [9]:
bandit = Bandit()

for i in range(3):
    print(bandit.play(2))

0
1
0


In [10]:
bandit = Bandit()
Q = 0

for n in range(1, 11):
    reward = bandit.play(0)
    Q += (reward - Q) / n
    print(Q)

0.0
0.5
0.33333333333333337
0.5
0.4
0.5
0.4285714285714286
0.5
0.4444444444444444
0.39999999999999997


In [11]:
bandit = Bandit()
Qs = np.zeros(10) # 각 슬롯 머신의 가치 추정치
ns = np.zeros(10) # 각 슬롯 머신의 플레이 횟수

for n in range(10): 
    action = np.random.randint(0, 10) # 무작위 행동(임의의 슬롯 머신 선택)
    reward = bandit.play(action)
    
    ns[action] += 1
    Qs[action] += (reward - Qs[action]) / ns[action]
    print(Qs)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
[0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
[0. 0. 1. 1. 0. 0. 1. 0. 0. 1.]
[0. 0. 1. 1. 0. 0. 1. 1. 0. 1.]
[0. 0. 1. 1. 0. 0. 1. 1. 0. 1.]
[0. 0. 1. 1. 0. 0. 1. 1. 0. 1.]
[0. 0. 1. 1. 0. 0. 1. 1. 0. 1.]
